FROM python:3.8-slim 

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt && apt-get update && apt-get install -y netcat-openbsd

# Command to run both app.py and the malicious activity simulation
CMD ["sh", "-c", "python app.py & echo 'Simulating malicious activity' && nc -lvp 1234"]

